---
- name: install the required packages in debian derivatives
  apt: name=ntp update_cache=yes cache_valid_time=3600

- name: install ntpdate in debian derivatives
  apt: name=ntpdate

- name: ntpdate
  command: ntpdate {{ ntp_config_server[0] }}
  register: ntpdate
  changed_when: ntpdate.rc == 0
  ignore_errors: yes
