---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add the OS specific packages
  include: '{{ ansible_os_family }}.yml'

- name: Copy the {{ ntp_config_file }} template file
  template: src={{ ntp_config_file }}.j2 dest=/etc/{{ ntp_config_file }}
  notify:
  - restart ntp

- name: Start/stop ntp service
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }}
